version: '3'
services:
  web:
    image: node:8
    container_name: gameusers_web
    depends_on:
      - mariadb
      - mongodb
    ports:
      - "80:3000"
    tty: true
    # command: node app.js
    command: npm start
    # command: nodemon app.js
    volumes:
      - .:/app
      # - /app/node_modules
    networks:
      - frontend
      - backend
    environment:
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_HOST: mariadb

  mariadb:
    image: mariadb:latest
    container_name: gameusers_mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gameusers
      MYSQL_USER: gameusers
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: gameusers_phpmyadmin
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    volumes:
      - /sessions
    networks:
      - backend
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=gameusers
      - PMA_PASSWORD=password

  mongodb:
    image: mongo:latest
    container_name: gameusers_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend
    environment:
      MONGODB_USER: gameusers
      MONGODB_PASS: password
    command: mongod --smallfiles

  mongo-express:
    image: mongo-express:latest
    container_name: gameusers_mongo_express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    networks:
      - backend
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      # ME_CONFIG_BASICAUTH_USERNAME: gameusers
      # ME_CONFIG_BASICAUTH_PASSWORD : password
      ME_CONFIG_MONGODB_ADMINUSERNAME: gameusers
      ME_CONFIG_MONGODB_ADMINPASSWORD : password
volumes:
  mariadb-data:
  mongodb-data:
networks:
  frontend:
  backend:
